name: hi
on:
  pull_request:

jobs:
  w:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            :)
          repo-token: ${{ secrets.SYNPAT }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false
