name: hi
on:
  pull_request:

jobs:
  w:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: read/write
      discussions: write
      checks: write
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            :)
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false
