name: hi
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: lol
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: :)
